version: '3.8'

services:

  db_stefanini:
    image: postgres:14.5-alpine
    container_name: db_stefanini
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stefanini_db      
    ports:
      - '5432:5432'


  pgadmin-stefanini:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-stefanini
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@patito.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db_stefanini